language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
# - https://stackoverflow.com/questions/33512541/
  - cd / ; sudo wget -c "https://launchpad.net/ubuntu/+source/python2.7/2.7.6-8/+build/5838314/+files/libpython2.7-dev_2.7.6-8_armhf.deb" ; sudo dpkg -x libpython2.7-dev_*_armhf.deb . ; cd -
  - cd / ; sudo wget -c "https://launchpad.net/ubuntu/+source/python2.7/2.7.6-8/+build/5838314/+files/libpython2.7_2.7.6-8_armhf.deb" ; sudo dpkg -x libpython2.7-dev_*_armhf.deb . ; cd -
  - sudo apt-get -y install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
  - wget https://ftp.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.0.25.tar.bz2
  - tar xf alsa-lib-1.0.25.tar.bz2
  - cd alsa-lib-1.0.25
  - CC=arm-linux-gnueabihf-gcc ./configure --prefix=/ --host=arm-linux-gnueabihf
  - make
  - sudo make install DESTDIR=/usr/arm-linux-gnueabihf/
  - cd ..
  - VERSION=2.5.5
#  - VERSION=$(wget -q "https://trac.pjsip.org/repos/browser/pjproject/tags?order=date&desc=1" -O - | grep "View Directory" | cut -d ">" -f 2 | cut -d "<" -f 1 | head -n 1)
  - wget http://www.pjsip.org/release/$VERSION/pjproject-$VERSION.tar.bz2
  - tar xf pjproject-*.tar.bz2
  - cd pjproject-*/
  - CC=arm-linux-gnueabihf-gcc ./configure --enable-static --disable-video --disable-libyuv --disable-sdl --disable-ffmpeg --disable-v4l2 --host=arm-linux-gnueabihf --prefix=/usr
  - make dep
  - make
  - find pjsip-apps/bin -type f -executable -exec arm-linux-gnueabihf-strip {} \;
  - tar cfvj ../pjsip-apps-$VERSION.tar.bz2 pjsip-apps/bin/
  - cd ..
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./pjsip-apps-*.tar.bz2
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
