language: none
sudo: required

env:
  - ARCH=x64
  - ARCH=arm

script:
  - bash -ex .travis.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
