language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - sudo apt-get -y install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
  - wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.0.25.tar.bz2
  - tar xf alsa-lib-1.0.25.tar.bz2
  - cd alsa-lib-1.0.25
  - CC=arm-linux-gnueabihf-gcc ./configure --prefix=/ --host=arm-linux-gnueabihf
  - make
  - sudo make install DESTDIR=/usr/arm-linux-gnueabihf/
  - cd ..
  - VERSION=1.12
#  - VERSION=$(wget -q "https://trac.pjsip.org/repos/browser/pjproject/tags?order=date&desc=1" -O - | grep "View Directory" | cut -d ">" -f 2 | cut -d "<" -f 1 | head -n 1)
  - wget http://www.pjsip.org/release/$VERSION/pjproject-$VERSION.tar.bz2
  - tar xf pjproject-*.tar.bz2
  - cd pjproject-*/
  - CC=arm-linux-gnueabihf-gcc  ./configure --host=arm-linux-gnueabihf --prefix=/usr
  - make dep
  - make
  - find pjsip-apps/bin -type f -executable -exec arm-linux-gnueabihf-strip {} \;
  - tar cfvj ../pjsip-apps-$VERSION.tar.bz2 pjsip-apps/bin/
  - cd ..
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./pjsip-apps-*.tar.bz2
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
